### PR TITLE
GDAES-1413 version is different for custom pkg

### PR DESCRIPTION
**Pull request by rgindes**

### CODE REVIEW

**Comment by janeves** [comment]
add to whitelist


Jason Neves | Senior Solutions Architect

Gannett Digital

Chesapeake Office: (757)624-2687 | Mobile: (757)470-3285
jneves@gannett.com<mailto:jneves@gmti.gannet.com>

**Comment by janeves** [comment]
Add to whitelist

**Comment by janeves** [comment]
test this please

**Comment by fhanson** [comment]
ok to test

**Pull request merged**
